# For development use
# Run all by executing: docker compose up
version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
      args:
        - MYSQL_HOST=mysql:3306
        - MYSQL_SCHEMA=mockdb
        - MYSQL_USER=root
        - MYSQL_PASSWORD=mockpass
        - JWT_SECRET=SMFZT8E6V6KSMA8VMFZYR9VZ9U3UQCOU
    ports:
      - 8080:8080
    networks:
      - frontend
      - backend
    depends_on:
      - mysql
    links:
      - mysql
    

  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - frontend
    
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=mockdb
      - MYSQL_ROOT_PASSWORD=mockpass
    ports:
      - 3306:3306
    networks:
      - backend
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=mockpass
      - PMA_ARBITRARY=1
    networks:
      - backend
    logging:
      driver: none


volumes:
  mysql-data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
